version: "3.9"

services:
  db:
    image: postgres:16
    container_name: emperor_db
    restart: always
    environment:
      POSTGRES_USER: emperor
      POSTGRES_PASSWORD: emperor_password
      POSTGRES_DB: emperor_bookmarks
    ports:
      - "5432:5432"
    volumes:
      - emperor_db_data:/var/lib/postgresql/data

  api:
    build: ./packages/api
    container_name: emperor_api
    restart: always
    environment:
      DATABASE_URL: postgres://emperor:emperor_password@db:5432/emperor_bookmarks
      JWT_SECRET: "super-secret-change-me"
    ports:
      - "4000:4000"
    depends_on:
      - db

volumes:
  emperor_db_data:
