services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: emperor_api
    restart: always
    environment:
      DATABASE_URL: postgresql://emperor:emperor_password@db:5432/emperor_bookmarks?schema=public
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: emperor_db
    restart: always
    environment:
      POSTGRES_USER: emperor
      POSTGRES_PASSWORD: emperor_password
      POSTGRES_DB: emperor_bookmarks
    ports:
      - "5432:5432"
    volumes:
      - emperor_db_data:/var/lib/postgresql/data

volumes:
  emperor_db_data:
